spring:
  profiles:
    #    active: home
    #active: HWCloud
    active: LiXiang
  application:
    name: SpringBootWebStarter
#
server:
  port: 8080
  servlet:
    context-path: /api
cors:
  enable: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

sa-token:
  token-name: Authorization

# Sa-Token-Quick-Login 配置
sa:
  # 登录账号
  name: shaoxiongdu
  # 登录密码
  pwd: dsx05117218
  # 是否自动随机生成账号密码 (此项为true时, name与pwd失效)
  auto: false
  # 是否开启全局认证(关闭后将不再强行拦截)
  auth: true
  # 登录页标题
  title: 管理员登录
  # 是否显示底部版权信息
  copr: false
  # 指定拦截路径
  # include: /**
  # 指定排除路径
  # exclude: /1.jpg
